Feature/#18
TeamCatchMe/CatchMe-If-You-Android pull request #33
Opened 2021-07-07 07:32 UTC by lydiacho

## Related Issues
#18 

## What Did You Do?
- [x] 메인 뷰 그리기 첫 시도
- [x] 생성 뷰 첫 페이지 그리기 시도!
- [ ] 네이밍이랑 건너뛴 부분들 조금 더 보완  

<div align="center">
<img height="500" src="https://user-images.githubusercontent.com/81505421/124717886-8360eb00-df40-11eb-8314-f0dd2b08092c.png"> 
<img height="500" src="https://user-images.githubusercontent.com/81505421/124717978-9a074200-df40-11eb-899d-67ad95aa078a.png">
</div>

2021-07-07 08:20 UTC, SeojinSeojin requested changes
수고 진짜 많았어~~ 첫 풀리퀘 축하만빵이닷 🎉🎉

2021-07-07 08:20 UTC, SeojinSeojin commented on app/src/main/java/com/teamcatchme/catchme/presentation/home/AddCatchuActivity.kt
> +    }
나중에 바인딩 액티비티 상속받는 걸로 고쳐주셔유~

```kotlin
class AddCachuActivity : BindingActivity<ActivityAddCachuBinding>(R.layout.activity_add_cachu){
	...
}
```

2021-07-07 08:20 UTC, SeojinSeojin commented on app/src/main/res/layout/activity_add_catchu.xml
> +        android:id="@+id/iv_btn_close"
네이밍!!
imageView라서 iv라고 시작해도 되지만 이 친구는 "닫는 동작을 해주는 버튼"인 것이니까

`@+id/btn_addcachu_close`
이런 식으로 하면 좋을 것 같다!

2021-07-07 08:20 UTC, SeojinSeojin commented on app/src/main/res/layout/activity_add_catchu.xml
> +        android:id="@+id/tv_header1"
tv도 좋지만 네이밍 컨벤션에서 txt로 하자고 했으
그리고 이 친구가 하는 일은 description 정도니까
`@+id/txt_addcachu_description`
이런 식으로 하면 좋을 것 같다!

2021-07-07 08:20 UTC, SeojinSeojin commented on app/src/main/res/layout/activity_add_catchu.xml
> +        android:textSize="22sp"
sp로 하면 사용자 설정에 따라 깨질 수 있다고 해.. 
물론 안드 스튜디오에서 정석은 sp로 하는건데 리드님께서 다 dp로 바꾸라고 하셨다!
왜냐면 사용자가 시스템 글씨 설정을 크거나 작게 했을 때 sp로 하면 다 깨지기 때문에 안 깨지려면 dp가 안정적이야

약간 안드 스튜디오에서 밤/낮 모드 다 개발하는거 권장하지만 우리는 다크모드 무시하는 것과 같은 그런 느낌으로
sp 싹 무시하고 dp로 가자~

2021-07-07 08:20 UTC, SeojinSeojin commented on app/src/main/res/layout/activity_add_catchu.xml
> +        tools:text="내 모습을 가장 잘 보여주는 캐츄를 골라주세요"
이 친구는 액티비티에 실제로 보여야 하는 내용이니까 android:text= ~~로 해도 좋을 듯해!!

2021-07-07 09:22 UTC, l2hyunwoo requested changes
뷰를 봤을 때 전반적으로 정해진 치수로 width나 height를 설정한 경우가 많네, 이 부분은 wrap_content나 (match_parent + margin)으로 바꿀 수 있으면 바꿔보는게 좋을 것 같아

2021-07-07 09:22 UTC, l2hyunwoo commented on app/build.gradle.kts
> +    implementation("androidx.constraintlayout:constraintlayout:2.0.4")
지웁시다

2021-07-07 09:22 UTC, l2hyunwoo commented on app/src/main/res/drawable/shape_black_graystroke_rectangular_48.xml
> +</shape>
이 부분은 어디서 사용하는거니?

2021-07-07 09:22 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_add_catchu.xml
> +        android:layout_marginTop="31dp"
웬만하면 4의 배수로! (Material Design 기준)

2021-07-07 09:22 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_add_catchu.xml
> +        android:layout_marginTop="21dp"
이것도 마찬가지!

2021-07-07 09:22 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_add_catchu.xml
> +        android:textColor="#ffffff"
이미 스타일 가이드에 @color/white 저장해놨어 그거 사용하면 됨

2021-07-07 09:22 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_add_catchu.xml
> +        android:id="@+id/tv_header2"
내가 봤을 때 tv_header2는 어떤 역할을 하는 텍스트뷰인지 감이 안와. txt_(어디서)_(어떤 역할) 이 형식으로 xml id 작성하는 걸 권장할게

2021-07-07 09:22 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_home.xml
> +        android:layout_height="174dp"
```suggestion
        android:layout_width="174dp"
        android:layout_height="0dp"
        app:layout_constraintDimensionRatio="1"
```

- 이 부분은 굳이 정해진 dp로 설정해야하는 이유가 있니? 아니면 wrap_content로 설정해도 좋을 것 같아
- 위와 같이 작성해도 정사각형 이미지로 나옴 참고해보셈

2021-07-07 09:22 UTC, l2hyunwoo commented on build.gradle.kts
> +    val kotlin_version by extra("1.5.10")
이것도 지워주시고!

2021-07-07 13:56 UTC, lydiacho commented on app/src/main/res/drawable/shape_black_graystroke_rectangular_48.xml
> +</shape>
메인뷰 활동리포트를 감싸는 상자입니다~~~!!~!

2021-07-07 13:58 UTC, lydiacho commented on app/src/main/res/layout/activity_add_catchu.xml
> +        android:textColor="#ffffff"
@l2hyunwoo 근데 혹시 제플린 코드에서 #____코드 사용해도 그거 다 @color에 있는 애들로 바꿔줘야할까유?

2021-07-07 14:01 UTC, lydiacho commented on app/src/main/res/layout/activity_home.xml
> +        android:layout_height="174dp"
@l2hyunwoo 제플린에있던 수치인데 캐릭터 더미파일에있는 크기랑 다르길래 새로 지정해준거! 아래 코드로 바꿀게

2021-07-07 15:12 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_add_catchu.xml
> +        android:textColor="#ffffff"
@lydiacho 아 제플린에서 #___이런 코드 썼을때에는 @color에서 비슷한 색이 있는지 찾고 없으면 따로 #__ 써주셈

2021-07-07 15:15 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_home.xml
> +        android:layout_height="174dp"
@lydiacho 저장되어있는 파일크기에 맞추는게 좋을 것 같아. 저 사진에는 저 캐릭터만 들어있는게 아니라 다른 사진도 들어갈 수 있는거 아닌가?

2021-07-08 02:06 UTC, SeojinSeojin approved these changes
id 하나하나 바꾸는게 쉽지 않은 일들인데 진짜 수고 많았다!!!

2021-07-08 02:06 UTC, SeojinSeojin commented on app/src/main/res/layout/main_card_item.xml
> +        android:layout_marginHorizontal="40dp"/>
리뷰 엄청 꼼꼼하게 잘 반영했네!!! 최고닷
코딩 컨벤션에 적히진 않았는데 사실 이런 리사이클러뷰 아이템들은 `item_main_card.xml` 이렇게 item이 맨 앞에 오도록 하더라구!! 그 점만 반영해주면 좋을 것 가타

2021-07-08 02:29 UTC, l2hyunwoo approved these changes
리뷰 잘 반영해준 것 같아 아주 굳

2021-07-08 02:29 UTC, l2hyunwoo commented on app/src/main/java/com/teamcatchme/catchme/presentation/home/MainCardActivity.kt
> +            val catchuItem = CatchuItem(name = "숭해숭해숭해숭해 $i")
이런 경우에는 아래와 같이 적을 수 있음

```kotlin
repeat(9) { catchList.add(CatchItem("${숭해숭해숭해숭해 $it}")) } 
```

2021-07-08 02:29 UTC, l2hyunwoo commented on app/src/main/java/com/teamcatchme/catchme/presentation/home/MainCardAdapter.kt
> +    }
- 굳이 ArrayList를 사용하지 않고 MutableList 사용해도 될 듯(ArrayList는 자바 문법이라서 ㅎ)
- 얘는 리스트를 바꾸면 notifyDataSetChanged도 해줘야겠쥬?
- 이렇게 코드를 구성하면 외부에서 catchuList라는 변수를 만들고 submitList로 어댑처에 있는 catchList를 바꿀 때 외부에 있는 catchuList로 어댑터 내부에 있는 catchuList를 조작할 수 있음(둘이 같은 주소를 공유함) 아래와 같이 바꿔보셈

```kotlin
fun submitList(catchuList: MutableList<CatchuItem>) {
    this.catchuList = catchuList.toMutableList // 객체를 복사해서 넘겨줌
    notifyDataSetChanged()
}
```

2021-07-08 02:29 UTC, l2hyunwoo commented on app/src/main/java/com/teamcatchme/catchme/presentation/home/MainCardViewHolder.kt
> +}
이건 굳이 외부로 안빼도 어댑터 내부에 중첩클래스로 정의가 가능할 것 같아. 어댑터하고 뷰홀더 왔다갔다하는게 은근 귀찮아서

2021-07-11 17:44 UTC, SeojinSeojin approved these changes
처음에 눈에 띄었던 긴 onCreate 부분 코드도 아주 잘 리팩토링했고 지금까지 코드상에는 문제가 없어 보여!!

다만 커밋 하나에 담긴 내용들이 많은 편인 것으로 보인다 ..

여기서 6번째 커밋에 있는 내용은
* 코드 리팩토링 (요것도 `1. onCreate 쪼개기` `2. spannableStringBuilder 리팩토링` 두개로 쪼갤 수 있을 것 가타)
* Home의 ViewPager 로직 코드 작성
* Main Card Item의 RecyclerView 로직 코드 작성
* xml 새로 짜는 작업
* xml 리팩토링 작업

등등.. 엄청나게 많은 일들을 하고 있어!!
사실 이거 짜다가 저거 생각나고 저거 짜다가 이거 고쳐야 할 것 같고 그러는게 사람 마음이지만!
작업 단위를 쪼개서 그 일만 집중하고 그 일 관련된 코드만 숑숑 수정해서 커밋하면 좋을 것 가타 🦒

2021-07-11 17:44 UTC, SeojinSeojin commented on app/src/main/java/com/teamcatchme/catchme/presentation/home/AddCatchu2Activity.kt
> +                    }
onCreate 안에 넘 많은 것들이 있다!!
이 친구들이 공통적으로 사용하는 binding 친구는 클래스 안에선 어디에서든지 접근 가능한 친구니까 함수로 쪼개서 onCreate 밖으로 빼주자!! **함수 이름도 진짜 멋있게 지어야 해~**

2021-07-11 17:44 UTC, SeojinSeojin commented on app/src/main/java/com/teamcatchme/catchme/presentation/home/AddCatchu2Activity.kt
> +                        val spannable = SpannableStringBuilder(binding.txtAddcatchuCount.text)
이 친구는 43번째, 50번째, 53번째에서 동일하게 생성되니까 if문 앞으로 빼주어도 될 것 같아!

2021-07-11 17:44 UTC, SeojinSeojin commented on app/src/main/java/com/teamcatchme/catchme/presentation/home/AddCatchu2Activity.kt
> +                    if (text.length == 20) spanString(binding.txtAddcatchuCount, 0, 5)
굿굿굿!!

2021-07-12 08:24 UTC, lydiacho commented on app/src/main/res/layout/activity_main_card.xml
> +        />
와대박 개짱이야 흑또모지!!!!

2021-07-12 08:36 UTC, lydiacho commented on app/src/main/res/layout/main_card_item.xml
> +        android:layout_marginHorizontal="40dp"/>
반영완료😍

2021-07-12 08:36 UTC, lydiacho commented on app/src/main/java/com/teamcatchme/catchme/presentation/home/MainCardActivity.kt
> +            val catchuItem = CatchuItem(name = "숭해숭해숭해숭해 $i")
오 대박 첨봐 repeat

2021-07-12 14:37 UTC, merged