feature/#44
TeamCatchMe/CatchMe-If-You-Android pull request #46
Opened 2021-07-09 17:24 UTC by SeojinSeojin

## Related Issues
#44 

## What Did You Do?
- [x] 리포트 뷰에 캘린더 붙이기

## Reference
<div align="center">
<img src="https://user-images.githubusercontent.com/48249505/125115064-cb8d3280-e125-11eb-8a5f-9b61a530dd66.gif" width="400">
</div>

2021-07-10 02:47 UTC, l2hyunwoo requested changes
리뷰 해주신 분들 바꿔주세요

2021-07-10 02:47 UTC, l2hyunwoo commented on app/src/main/java/com/teamcatchme/catchme/presentation/report/ReportActivity.kt
> +                updateTxtUI(currentYear - 3 + (position / 12), (position % 12) + 1)
상수를 적을때에는 남들이 이걸 보고 어떤 역할을 하는 지 알 수 있어야됨. 내가 봤을 때 35는 어떤 의미인지 모르겠거든? 의미부여를 해줬으면 해

2021-07-10 02:50 UTC, SeojinSeojin commented on app/src/main/java/com/teamcatchme/catchme/presentation/report/ReportActivity.kt
> +                updateTxtUI(currentYear - 3 + (position / 12), (position % 12) + 1)
- 무한스크롤 가능하도록 수정하자
- 가독성 좋게 수정하자

2021-07-10 02:52 UTC, SeojinSeojin commented on app/src/main/java/com/teamcatchme/catchme/presentation/report/CalendarAdapter.kt
> +    private val yearList = mutableListOf<String>()
CachuData를 여기서 받아오자,.. 가릿

2021-07-11 09:17 UTC, l2hyunwoo approved these changes
수고 많이했어 이제 머지하자

2021-07-11 09:17 UTC, l2hyunwoo commented on app/src/main/java/com/teamcatchme/catchme/presentation/report/MonthlyAdapter.kt
> +            1
TYPE_DATE를 말하는거겠지?

2021-07-11 09:17 UTC, l2hyunwoo commented on app/src/main/java/com/teamcatchme/catchme/presentation/report/ReportActivity.kt
> +    }
굳

2021-07-11 09:17 UTC, l2hyunwoo commented on app/src/main/java/com/teamcatchme/catchme/presentation/report/ReportActivity.kt
> +        binding.btnReportDialogMoveRight.setOnClickListener { onArrowClicked(RIGHT) }
매우 좋음 한 눈에 어떤 역할을 하는지 바로 알 수 있었어

2021-07-11 09:20 UTC, SeojinSeojin commented on app/src/main/java/com/teamcatchme/catchme/presentation/report/MonthlyAdapter.kt
> +            1
이거는 첫번째 날의 요일 받아오려고 1일로 지정한겨 !!

2021-07-11 09:24 UTC, merged