Feature/#80 둘러보기 뷰 구현
TeamCatchMe/CatchMe-If-You-Android pull request #91
Opened 2021-07-13 19:26 UTC by lydiacho

## Related Issues
#80

## What Did You Do?
- [x] 둘러보기 뷰 구현
- [x] 둘러보기 recyclerview 구현
- [x] 버튼클릭리스너 연결
- [ ] 화면전환 애니메이션 넣어야함(넣을 수 있도록 finish()해둠) (부제 : anim은 어디에)

<img src="https://user-images.githubusercontent.com/81505421/125512979-c525d625-dc84-46af-829e-dfa763c7602e.png" width="200">

2021-07-13 19:31 UTC, lydiacho commented on app/src/main/res/layout/item_look.xml
> +            android:layout_width="150dp"
참고로 요 아가 왜 width를 정적으로 줬냐! 하신다면...
이름을 두줄로 만들기 위하여 제플린에서 고정적인 텍뷰사이즈를 줬기 때문이랍니당
근데 그렇게 하니까 너무 좁은거예요 저희꺼에서 
그래서 텍스트 개행되는 위치 똑같도록 사이즈 조절한거고 아마 폰트 적용하면 또 조금 달라질 수 있을 것 같습니당

다른 방법이 있다면 배우겠습니다 꾸벅스

2021-07-14 00:28 UTC, SeojinSeojin commented on app/src/main/res/layout/item_look.xml
> +            android:layout_width="150dp"
나두 범위 정적으로 줘야 되는 친구들은 다 고정 높이로 줬어!

2021-07-14 02:14 UTC, SeojinSeojin approved these changes
수고 많았으!! 지워야 하는 부분만 지우고 커밋하고 머지하면 될듯혀

2021-07-14 02:14 UTC, SeojinSeojin commented on app/build.gradle.kts
> +    implementation("androidx.constraintlayout:constraintlayout:2.0.4")
요 부분 지워야 한당

2021-07-14 02:14 UTC, SeojinSeojin commented on build.gradle.kts
> +    val kotlin_version by extra("1.5.10")
요부분도 ..!

2021-07-14 02:32 UTC, l2hyunwoo requested changes
지울거 지우고 다시 한번 커밋 푸시 고고

2021-07-14 02:32 UTC, l2hyunwoo commented on app/src/main/java/com/teamcatchme/catchme/presentation/home/HomeActivity.kt
> +
빈칸 지우기!

2021-07-14 02:32 UTC, l2hyunwoo commented on app/src/main/java/com/teamcatchme/catchme/presentation/look/LookActivity.kt
> +    }
companion object는 클래스 맨 마지막에!(코틀린 스타일 가이드)

2021-07-14 02:32 UTC, l2hyunwoo commented on app/src/main/java/com/teamcatchme/catchme/presentation/look/LookActivity.kt
> +    }
매개변수로 space 받는 건 굳, 이건 범용성 있게 만들기 위해서라면 어떻게 설계하는게 좋을까?

2021-07-14 02:36 UTC, lydiacho commented on app/src/main/java/com/teamcatchme/catchme/presentation/look/LookActivity.kt
> +    }
@l2hyunwoo 인자로 멀 더 받아야하나유,,,? 범용성.... ㅜ

2021-07-14 02:37 UTC, l2hyunwoo commented on app/src/main/java/com/teamcatchme/catchme/presentation/look/LookActivity.kt
> +    }
음 예를 들어서 저건 bottom, top에만 space를 줄 수 있지만, left, right에도 space를 주는 경우도 있지 않을까? 이 경우에는 저 ItemDecoration을 어떻게 설계하는 것이 좋을까?

2021-07-14 07:53 UTC, l2hyunwoo approved these changes

2021-07-14 07:53 UTC, merged